config/routes.rb
Rails.application.routes.draw do
  
 
  root 'recipes#index'


  

  resources :users, controller: "users" 
  resources :sessions, controller: "sessions"
 
  get "/sign_up" => "users#new", as: "sign_up"
  get "/users/show" => "users#show", as: "profile"

  post "/sessions/new" => "sessions#create"
  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"

  get "/recipes/gimmick" => "recipes#gimmick", as: "gimmick"
  get "/recipes/index" => "recipes#index", as: "recipes_index"
  get "/recipes/new" => "recipes#new", as: "create_recipe"
  post "/recipes/new" => "recipes#create" 
  post "/recipes/search" => "recipes#search", as: "search_recipes"
  get "/recipes/random" => "recipes#random", as: "random_recipe"
  get "/recipes/:id" => "recipes#show", as: "recipe_show"

  resources :recipes, controller: "recipes" 


  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user


	def self.create_with_omniauth(auth_hash)
	   self.new(
	     provider: auth_hash["provider"],
	     uid: auth_hash["uid"],
	     token: auth_hash["credentials"]["token"]
	   )
	end

	def update_token(auth_hash)
	   self.token = auth_hash["credentials"]["token"]
	   self.save
	end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	belongs_to(:user)
	self.per_page = 9


	def self.humding

		y = self.last
		c = y.title.reverse
		d = y.description.reverse
		z = []
		z.push(c)
		z.push(d)
		return z

	end

	def self.balthasar
		y = self.last
		if y.title == "dum"
			z = []
			c = y.description.upcase
			d = y.description.downcase
			z.push(c)
			z.push(d)
			return z
		else
			z = []
			c = y.description.upcase
			z.push(c)
			return z
		end
	end

end

app/models/user.rb
class User < ApplicationRecord
	 has_secure_password

	 validates :email, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}, presence: true
   validates :name, uniqueness: true, presence: true

	 has_many(:recipes)

	 has_many :authentications, dependent: :destroy

	 def self.create_with_auth_and_hash(authentication, auth_hash)
      user = self.create!(
        name: auth_hash["extra"]["raw_info"]["name"],
        email: auth_hash["extra"]["raw_info"]["email"],
        password: SecureRandom.hex(4)
      )
      user.authentications << authentication
      return user
    end

    # grab fb_token to access Facebook for user data
    def fb_token
      x = self.authentications.find_by(provider: 'facebook')
      return x.token unless x.nil?
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

	def current_user
    	@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def signed_in?
		!current_user.nil?
	end
	helper_method :current_user, :signed_in?
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	
	def index
		if signed_in?
			@recipes = current_user.recipes
		else
			redirect_to sign_in_path
		end
	end


	def search
		@z = "%#{params[:query]}%"
		@recipes = Recipe.where("title ILIKE ? or description ILIKE ?", @z, @z)
		render "index"
	end


	def random

	end


	def new

	end

	def show 
		@recipe = Recipe.find(params[:id])
		respond_to do |format|
			format.js {}
			format.html {}
		end
	end

	def create
		@recipe = Recipe.new(recipe_params)
		@recipe.user_id = current_user.id
		if @recipe.save
	      redirect_to recipes_index_path
	    else
	      redirect_to profile_path
	    end
	end


	def recipe_params	
	    params.require(:recipe).permit(:title, :description)
	end

	def gimmick

	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController	

	def new

	end

	def create
		@user = User.find_by(email: params[:session][:email])
		if @user && @user.authenticate(params[:session][:password])
	    	session[:user_id] = @user.id
	    	redirect_to recipes_index_path
		else
	    	redirect_to sign_in_path
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_path
	end




	def create_from_omniauth
      auth_hash = request.env["omniauth.auth"]
      authentication = Authentication.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"]) ||  Authentication.create_with_omniauth(auth_hash)

      # if: previously already logged in with OAuth
      if authentication.user
        user = authentication.user
        authentication.update_token(auth_hash)
        @notice = "Signed in!"
      # else: user logs in with OAuth for the first time
      else
        user = User.create_with_auth_and_hash(authentication, auth_hash)
        # you are expected to have a path that leads to a page for editing user details
        @notice = "User created. Please confirm or edit details"
      end

      session[:user_id] = user.id
      redirect_to profile_path, :notice => @notice
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new

	end

	def show
		
	end

	def create
		@user = User.new(user_params)
		if @user.save
	      redirect_to sign_in_path
	    else
	      redirect_to root_path
	    end
	end


	def user_params	
	    params.require(:user).permit(:email, :name, :password)
	end
	


	






end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeBook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="shadow-box">
  	<ul>
	  	<%if signed_in? %>
	      <li><%= button_to("Sign Out", sign_out_path, method: :delete) %></li>
	      <div class="log-in-status"><li>Logged-In As: <%=current_user.name%></li></div>
	    <% else %>

	     
	        <li><%= button_to("Sign In", sign_in_path, method: :get) %></li>

	     	

	        <li><%= button_to("Sign Up", sign_up_path, method: :get) %></li>
	        <div class="log-in-status"><li>You are not currently logged in</li></div>

	    <% end %>

	    <li><%= button_to("All Recipes", recipes_index_path, method: :get) %></li>

	    <li><%= button_to("New Recipe", create_recipe_path, method: :get) %></li>

	    <li><%= button_to("Get Random Recipe", random_recipe_path, method: :get) %></li>
	    <div class="log-in-status"><li><%= button_to("Just a funny gimmick", gimmick_path, method: :get) %></li></div>
	</ul>


    <%= yield %>
  </div>  
  </body>
</html>

app/views/recipes/_form.html.erb
<h3>Please enter your recipe</h3>

<div class="text-field">
  <%= form.text_field :title, type: 'title', placeholder: "Title of Recipe" %>
</div>

<div class="text-field">
  <%= form.text_area :description, cols: 40, rows: 15, type: 'description', placeholder: "Enter your recipe" %>
</div>

<div class="submit-field">
  <%= form.submit %>
</div>

app/views/recipes/gimmick.html.erb
<%= Recipe.humding %>
<br>
<%= Recipe.balthasar %>

app/views/recipes/index.html.erb
<%= form_tag search_recipes_path do %>

<input class="searchbar" name="query" placeholder="Search For Recipes" type="text" autocomplete="off">

<%end%>

<h1>All of your recipes</h1>

<% @posts = @recipes.paginate(:page => params[:page]) %>

<% @posts.each do |x| %>
	<div class="index-1">
		<h2><%= x.title %></h2>
		<div id='recipe-<%= x.id %>'>
		</div>
		<%= button_to 'See Instructions', recipe_show_path(x.id), remote: true, method: :get %>
	</div>
<% end %>

<%= will_paginate @posts, :page_links => true %>

app/views/recipes/new.html.erb
<h1>Create Recipe</h1>

<%= form_for :recipe do |form| %>
	<%= render partial: '/recipes/form', object: form %>
<%end%>

app/views/recipes/random.html.erb
<% request = RestClient.get("http://food2fork.com/api/get?key=#{ENV['F2F_API_KEY']}&rId=#{rand(1000..9999)}") %>



<h1><%= JSON.parse(request.body)["recipe"]["title"].html_safe %></h1>




<a class="recipe-link" target="_blank" href="<%= JSON.parse(request.body)["recipe"]["source_url"] %>"><h3>See Full Recipe </h3></a>

app/views/recipes/show.html.erb
<p><%= @recipe.description %></p>

app/views/recipes/show.js.erb
$('#recipe-<%= @recipe.id %>').html('<%= escape_javascript(@recipe.description).gsub("\\n","<br>").html_safe %>')

app/views/users/_form.html.erb
<h3>Please enter your details</h3>

<div class="text-field">
  <%= form.text_field :name, type: 'name', placeholder: "What's your name" %>
</div>

<div class="text-field">
  <%= form.text_field :email, type: 'email', placeholder: "What's your email" %>
</div>

<div class="password-field">
  <%= form.password_field :password, placeholder: "What's your password" %>
</div>

app/views/users/new.html.erb
<h1>Sign Up Page</h1>
<%= form_for User.new do |form| %>

	<%= render partial: '/users/form', object: form %>
	<%= form.submit %>
	
<%end%>


	

app/views/users/show.html.erb
<h1>Your Profile</h1>

<h4>Name: <%= current_user.name %></h4>

<h4>E-Mail: <%= current_user.email %></h4>

<h4>Number of Recipes: <%= current_user.recipes.count %></h4>